language: php

env:
  - NETTE=default # 2.4
  - NETTE=nette-dev

php:
  - 5.6
  - 7.0
  - 7.1


before_script:
  - "php tests/prepare-composer.php"
  - composer self-update
  - composer install --no-interaction --prefer-source
  - ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .

script: ./vendor/bin/tester -c ./tests/php.ini-unix ./tests/KdybyTests/

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
