language: php

env:
  - NETTE=default # 2.4
  - NETTE=nette-dev

php:
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - env: NETTE=nette-dev

before_script:
  - "php tests/prepare-composer.php"
  - mkdir -p tests/_temp
  - mkdir -p tests/_tmp
  - composer self-update
  - composer install --no-interaction --prefer-source
  - ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .

script: ./vendor/bin/tester -c ./tests/phpUnix.ini ./tests/KdybyTests/

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
