language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4


before_script:
  - mkdir -p tests/_temp
  - mkdir -p tests/_tmp
  - mkdir temp/
  - composer self-update
  - composer create-project --no-interaction --no-progress --prefer-dist php-parallel-lint/php-parallel-lint temp/php-parallel-lint ~1.2
  - composer create-project --no-interaction --no-progress --prefer-dist nette/code-checker temp/code-checker ~2.9
  - composer install --no-interaction --prefer-source
  - temp/code-checker/code-checker --no-progress -d src
  - temp/code-checker/code-checker --no-progress -d tests/KdybyTests
  - temp/php-parallel-lint/parallel-lint -e php,phpt -j 8 --exclude tests/_temp --exclude temp --exclude vendor .

script:
  - ./vendor/bin/tester -c ./tests/phpUnix.ini ./tests/KdybyTests/

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
