name: Parallel Lint

on: [push, pull_request]

jobs:
    nette_pp:
        name: Parallel Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  coverage: none

            - run: composer create-project --no-interaction --no-progress --prefer-dist php-parallel-lint/php-parallel-lint temp/php-parallel-lint --no-dev "~1.3"
            - run: php temp/php-parallel-lint/parallel-lint -e php,phpt -j 8 --exclude tests/_temp --exclude temp --exclude vendor .
